#!/usr/bin/env python3
"""
Timing Diagram Generator for ZX Spectrum Hardware Documentation

Generates SVG timing diagrams for ULA, memory, and CPU signal interactions.
Theme-compliant with the waveform generator standards.

Reference: http://www.zxdesign.info/dynamicRam2.shtml
"""

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch, Rectangle
import numpy as np
import os
import sys
import inspect

# Theme dictionary matching waveform_generator standards
THEME = {
    'background': '#1a1a2e',
    'grid': '#2d2d44',
    'text': '#e0e0e0',
    'digital': '#00ff88',       # Green for digital signals
    'analog': '#ff6b6b',        # Red for analog/error states
    'highlight': '#ffd93d',     # Yellow for highlights
    'muted': '#6c7a89',         # Gray for inactive
    'accent1': '#4ecdc4',       # Cyan
    'accent2': '#ff8c42',       # Orange
    'accent3': '#a855f7',       # Purple
}

def apply_theme(fig, axs):
    """Apply dark theme to figure and axes."""
    fig.patch.set_facecolor(THEME['background'])
    if not hasattr(axs, '__iter__'):
        axs = [axs]
    for ax in axs:
        ax.set_facecolor(THEME['background'])
        ax.tick_params(colors=THEME['text'])
        ax.xaxis.label.set_color(THEME['text'])
        ax.yaxis.label.set_color(THEME['text'])
        ax.title.set_color(THEME['text'])
        for spine in ax.spines.values():
            spine.set_color(THEME['grid'])

def save_meta(filepath, generator_func):
    """Save metadata alongside SVG for reproducibility."""
    meta_path = filepath.replace('.svg', '.meta.md')
    source = inspect.getsource(generator_func)
    with open(meta_path, 'w') as f:
        f.write(f"# Generated by: {generator_func.__name__}\n\n")
        f.write("```python\n")
        f.write(source)
        f.write("\n```\n")

def draw_clock(ax, y_base, times, name, color=None, period=2):
    """Draw a clock waveform with proper square wave shape."""
    if color is None:
        color = THEME['digital']

    x_points = []
    y_points = []

    for t in range(times):
        cycle_pos = t % period
        if cycle_pos == 0:
            # Rising edge
            x_points.extend([t, t])
            y_points.extend([y_base, y_base + 0.8])
        elif cycle_pos == period // 2:
            # Falling edge
            x_points.extend([t, t])
            y_points.extend([y_base + 0.8, y_base])

        # Horizontal segment
        level = 0.8 if (t // (period // 2)) % 2 == 0 else 0
        if t < times - 1:
            x_points.append(t + 1)
            y_points.append(y_base + level)

    ax.plot(x_points, y_points, color=color, linewidth=1.5)
    ax.text(-0.8, y_base + 0.4, name, ha='right', va='center',
            color=THEME['text'], fontsize=9, fontweight='bold')

def draw_signal_transitions(ax, y_base, transitions, name, color=None):
    """
    Draw a digital signal from a list of (time, level) transitions.
    Level: 1 = high, 0 = low
    """
    if color is None:
        color = THEME['digital']

    x_points = []
    y_points = []

    for i, (t, level) in enumerate(transitions):
        if i > 0:
            # Vertical transition from previous level
            prev_level = transitions[i-1][1]
            x_points.extend([t, t])
            y_points.extend([y_base + prev_level * 0.8, y_base + level * 0.8])

        x_points.append(t)
        y_points.append(y_base + level * 0.8)

        # Extend horizontally to next transition
        if i < len(transitions) - 1:
            next_t = transitions[i + 1][0]
            x_points.append(next_t)
            y_points.append(y_base + level * 0.8)

    ax.plot(x_points, y_points, color=color, linewidth=1.5)
    ax.text(-0.8, y_base + 0.4, name, ha='right', va='center',
            color=THEME['text'], fontsize=9, fontweight='bold')

def draw_bus_values(ax, y_base, segments, name, color=None):
    """
    Draw a bus with value labels and optional hatching for transition regions.
    segments: list of (start_time, end_time, value_string)
    """
    if color is None:
        color = THEME['accent3']

    height = 0.7
    for start, end, value in segments:
        if start >= end:
            continue
        mid = (start + end) / 2

        if value == 'hatch':
            # Cross-hatched transition / undefined bus area
            xs = [start, end, end, start]
            ys = [y_base, y_base, y_base + height, y_base + height]
            ax.fill(xs, ys, color=color, alpha=0.3, hatch='///')
            ax.plot([start, end], [y_base, y_base + height], color=color, linewidth=0.8, alpha=0.6)
            ax.plot([start, end], [y_base + height, y_base], color=color, linewidth=0.8, alpha=0.6)
            ax.plot([start, start], [y_base, y_base + height], color=color, linewidth=0.8, alpha=0.6)
            ax.plot([end, end], [y_base, y_base + height], color=color, linewidth=0.8, alpha=0.6)
        elif value:
            # Draw X-style bus transitions
            # Left transition
            ax.plot([start, start + 0.15], [y_base + height/2, y_base + height],
                   color=color, linewidth=1.2)
            ax.plot([start, start + 0.15], [y_base + height/2, y_base],
                   color=color, linewidth=1.2)

            # Top and bottom lines
            ax.plot([start + 0.15, end - 0.15], [y_base + height, y_base + height],
                   color=color, linewidth=1.2)
            ax.plot([start + 0.15, end - 0.15], [y_base, y_base],
                   color=color, linewidth=1.2)

            # Right transition
            ax.plot([end - 0.15, end], [y_base + height, y_base + height/2],
                   color=color, linewidth=1.2)
            ax.plot([end - 0.15, end], [y_base, y_base + height/2],
                   color=color, linewidth=1.2)

            # Fill
            xs = [start + 0.15, end - 0.15, end - 0.15, start + 0.15]
            ys = [y_base, y_base, y_base + height, y_base + height]
            ax.fill(xs, ys, color=color, alpha=0.2)

            # Value label
            ax.text(mid, y_base + height/2, value, ha='center', va='center',
                   color=THEME['text'], fontsize=7, fontweight='bold')

    ax.text(-0.8, y_base + height/2, name, ha='right', va='center',
            color=THEME['text'], fontsize=9, fontweight='bold')

def generate_ula_video_access():
    """
    Generate ULA Video Access timing diagram showing DRAM Paged Mode RAS/CAS sequence.
    Accurately matches logic analyzer hardware traces (zxdesign.info/dynamicRam2.shtml).

    Clock / Timing Specifications:
    - MCLK = 14 MHz (71.45 ns per cycle)
    - CPU_CLK / z80_CLK = 3.5 MHz (4 MCLK cycles per period: 2 Low, 2 High)
    - C1 (Cursor 1) to C2 (Cursor 2) = 574.26 ns (8 MCLK cycles = 1 character fetch)
    - DRAM Paged Mode: /RAS stays LOW throughout the character fetch (t=0..7) while /CAS
      pulses twice for Pixel (t=1..3) and Attribute (t=5..7) data fetches.
    """
    fig, ax = plt.subplots(figsize=(16, 9))

    t_max = 16

    # 1. MCLK - 14 MHz Master Clock (period = 1 MCLK unit = 71.45 ns)
    x_mclk, y_mclk = [], []
    for i in range(t_max):
        x_mclk.extend([i, i + 0.5, i + 0.5, i + 1])
        y_mclk.extend([11.8, 11.8, 11.0, 11.0])
    ax.plot(x_mclk, y_mclk, color=THEME['digital'], linewidth=1.5)
    ax.text(-0.8, 11.4, 'MCLK', ha='right', va='center',
            color=THEME['text'], fontsize=9, fontweight='bold')

    # 2. CPU_CLK - 3.5 MHz (falling edge at t=0, t=4, t=8, t=12)
    cpu_transitions = [
        (0, 0), (2, 1), (4, 0), (6, 1), (8, 0), (10, 1), (12, 0), (14, 1), (16, 0)
    ]
    draw_signal_transitions(ax, 10, cpu_transitions, 'CPU_CLK', THEME['accent1'])

    # 3. z80_CLK - Z80 CPU Clock (aligned with CPU_CLK)
    z80_transitions = [
        (0, 0), (2, 1), (4, 0), (6, 1), (8, 0), (10, 1), (12, 0), (14, 1), (16, 0)
    ]
    draw_signal_transitions(ax, 9, z80_transitions, 'z80_CLK', THEME['muted'])

    # 4. /RAS - Row Address Strobe (Paged Mode: LOW for t=0..7, HIGH for t=7..8)
    ras_transitions = [
        (0, 0), (7, 1), (8, 0), (15, 1), (16, 1)
    ]
    draw_signal_transitions(ax, 7.5, ras_transitions, '/RAS', THEME['highlight'])

    # 5. /CAS - Column Address Strobe (2 pulses per 8 MCLK fetch: Pixel & Attr)
    cas_transitions = [
        (0, 1),
        (1, 0), (3, 1),   # 1st pulse (Pixel 0)
        (5, 0), (7, 1),   # 2nd pulse (Attr 0)
        (9, 0), (11, 1),  # 3rd pulse (Pixel 1)
        (13, 0), (15, 1), # 4th pulse (Attr 1)
        (16, 1)
    ]
    draw_signal_transitions(ax, 6.2, cas_transitions, '/CAS', THEME['accent2'])

    # 6. maddr - Multiplexed Address Bus
    maddr_segments = [
        (0, 1, '00'),        # Row Address (Char 0)
        (1, 3, '00'),        # Pixel Column Address
        (3, 3.5, 'hatch'),   # Transition
        (3.5, 5, '30'),      # Attribute Column Address
        (5, 7, 'hatch'),     # Transition
        (7, 8.5, '01'),      # Row Address (Char 1)
        (8.5, 9, 'hatch'),   # Transition
        (9, 11, '00'),       # Pixel Column Address (Char 1)
        (11, 11.5, 'hatch'), # Transition
        (11.5, 13, '30'),    # Attribute Column Address (Char 1)
        (13, 15, '00'),      # Bus idle
        (15, 16, '70'),      # Next Address State
    ]
    draw_bus_values(ax, 4.5, maddr_segments, 'maddr', THEME['accent3'])

    # 7. db - Data Bus
    db_segments = [
        (0, 2, 'FF'),
        (2, 4.5, '99'),      # Pixel byte 0 read
        (4.5, 6.5, '38'),    # Attribute byte 0 read
        (6.5, 8.5, '2C'),
        (8.5, 10.5, 'AA'),   # Pixel byte 1 read
        (10.5, 12.5, '2C'),
        (12.5, 14.5, '55'),  # Attribute byte 1 read
        (14.5, 15.5, 'hatch'),
        (15.5, 16, '16'),
    ]
    draw_bus_values(ax, 3.0, db_segments, 'db', THEME['muted'])

    # Grid vertical lines (every 1 MCLK cycle)
    for t in range(t_max + 1):
        ax.axvline(x=t, color=THEME['grid'], linestyle='-', alpha=0.3, linewidth=0.8)

    # Logic Analyzer Cursors
    # Cursor 1 (C1: 0, 37.777 us)
    ax.axvline(x=0, color='#3b82f6', linestyle='--', linewidth=1.5, alpha=0.9)
    ax.text(0, 12.5, ' C1: 0 ', color='#ffffff', fontsize=8, fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.2', facecolor='#3b82f6', edgecolor='none'))

    # Cursor 2 (C2: 1, 38.352 us, Delta: 574.26 ns)
    ax.axvline(x=8, color='#22c55e', linestyle='--', linewidth=1.5, alpha=0.9)
    ax.text(8, 12.5, ' C2: 1 ', color='#ffffff', fontsize=8, fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.2', facecolor='#22c55e', edgecolor='none'))

    ax.text(4, 12.5, 'Delta Time: 574.26 ns (8 MCLK cycles / 1 Char Fetch)',
            color=THEME['highlight'], fontsize=8.5, ha='center', va='center', fontweight='bold')

    # Annotations
    ax.annotate('RAS↓ (Paged Mode)\nRow latched for block', xy=(0, 7.5), xytext=(1.2, 1.8),
                color=THEME['highlight'], fontsize=8, ha='center',
                arrowprops=dict(arrowstyle='->', color=THEME['highlight'], lw=1.2))

    ax.annotate('1st CAS↓\nPixel byte read', xy=(1, 6.2), xytext=(3.0, 1.8),
                color=THEME['accent2'], fontsize=8, ha='center',
                arrowprops=dict(arrowstyle='->', color=THEME['accent2'], lw=1.2))

    ax.annotate('2nd CAS↓\nAttr byte read', xy=(5, 6.2), xytext=(5.5, 1.8),
                color=THEME['accent2'], fontsize=8, ha='center',
                arrowprops=dict(arrowstyle='->', color=THEME['accent2'], lw=1.2))

    # Styling
    ax.set_xlim(-1.5, 17)
    ax.set_ylim(1.2, 13.3)
    ax.set_xlabel('Time (71.45 ns / MCLK cycle)', fontsize=10)
    ax.set_title('ULA Video Access Timing — DRAM Paged Mode (RAS/CAS Sequence)\n'
                'Hardware Trace Reference: zxdesign.info/dynamicRam2.shtml',
                fontsize=11, fontweight='bold', pad=15)
    ax.set_xticks(range(0, 17, 2))
    ax.set_yticks([])

    apply_theme(fig, ax)
    plt.tight_layout()

    return fig

def generate_snow_collision():
    """
    Generate Snow Effect timing diagram showing RFSH collision with ULA RAS.
    Shows Z80 M1 refresh cycle overlapping ULA video fetch during DRAM Paged Mode.
    """
    fig, ax = plt.subplots(figsize=(14, 10))

    t_max = 12

    # hc counter values
    hc_segments = [
        (0, 2, 'hc=6'), (2, 4, 'hc=7'), (4, 6, 'hc=8'),
        (6, 8, 'hc=9'), (8, 10, 'hc=A'), (10, 12, 'hc=B')
    ]
    draw_bus_values(ax, 9, hc_segments, 'hc[3:0]', THEME['muted'])

    # CPU Clock (3.5 MHz = period of 4 CLK14)
    cpu_transitions = [(0, 0), (2, 1), (4, 0), (6, 1), (8, 0), (10, 1), (12, 0)]
    draw_signal_transitions(ax, 8, cpu_transitions, 'CPU_CLK', THEME['accent1'])

    # M1 cycle phases
    phase_segments = [
        (0, 2, 'T1'), (2, 4, 'T2'), (4, 8, 'T3-T4\n(RFSH)'), (8, 12, 'Next')
    ]
    draw_bus_values(ax, 7, phase_segments, 'M1 Phase', THEME['text'])

    # /MREQ - active during T1-T2 (opcode fetch) and T3-T4 (refresh)
    mreq_transitions = [
        (0, 1), (0.5, 0), (4, 1), (4.5, 0), (8, 1), (12, 1)
    ]
    draw_signal_transitions(ax, 6, mreq_transitions, '/MREQ', THEME['digital'])

    # /RFSH - active during T3-T4
    rfsh_transitions = [
        (0, 1), (4, 0), (8, 1), (12, 1)
    ]
    draw_signal_transitions(ax, 5, rfsh_transitions, '/RFSH', THEME['highlight'])

    # Address bus
    addr_segments = [
        (0, 4, 'PC (opcode)'),
        (4, 8, 'IR (I=#7E, R=#xx)'),
        (8, 12, 'PC+1')
    ]
    draw_bus_values(ax, 4, addr_segments, 'Address', THEME['accent2'])

    # ULA /RAS - falls at hc=8 (t=4) in Paged Mode
    ras_transitions = [
        (0, 1), (4, 0), (11, 1), (12, 1)
    ]
    draw_signal_transitions(ax, 3, ras_transitions, 'ULA /RAS', THEME['analog'])

    # Latched signals (sampled on CPU_CLK falling edge)
    latch_segments = [
        (0, 2, ''),
        (2, 6, 'MREQ=1\nRFSH=1'),
        (6, 10, 'MREQ=0\nRFSH=0'),
        (10, 12, 'MREQ=1')
    ]
    draw_bus_values(ax, 2, latch_segments, 'Latched\n(CPUClk↓)', THEME['muted'])

    # Collision highlight zone (full height covering all waveform lanes)
    ax.axvspan(4, 8, color=THEME['analog'], alpha=0.12, zorder=0)
    ax.axvline(x=4, color=THEME['analog'], linestyle='--', linewidth=1.5, alpha=0.8)
    ax.axvline(x=8, color=THEME['analog'], linestyle='--', linewidth=1.5, alpha=0.8)

    # Collision annotation
    ax.annotate('COLLISION!\nRFSH active when\nULA generates RAS\nat hc=8',
                xy=(6, 5.5), xytext=(10, 7.5),
                color=THEME['analog'], fontsize=9, fontweight='bold',
                ha='center', va='center',
                arrowprops=dict(arrowstyle='->', color=THEME['analog'], lw=2),
                bbox=dict(boxstyle='round', facecolor=THEME['background'],
                         edgecolor=THEME['analog']))

    # Explanation
    ax.text(9.5, 1.5,
            'ULA checks latched MREQ/RFSH\n'
            'at RAS generation time.\n'
            'Both active → R corrupts row addr',
            ha='center', va='center', color=THEME['text'], fontsize=8,
            bbox=dict(boxstyle='round', facecolor=THEME['background'],
                     edgecolor=THEME['grid'], alpha=0.9))

    # Timing markers
    for t in range(t_max + 1):
        ax.axvline(x=t, color=THEME['grid'], linestyle='-', alpha=0.3, linewidth=0.8)

    ax.text(4, 10.2, 'RAS↓', color=THEME['analog'], fontsize=8, ha='center')

    # Styling
    ax.set_xlim(-1.5, 13)
    ax.set_ylim(1, 10.5)
    ax.set_xlabel('Time (CLK14 periods)', fontsize=10)
    ax.set_title('Snow Effect — RFSH Collision with ULA Video Fetch\n'
                'ZX-48 only: ULA ignores /RFSH signal',
                fontsize=11, fontweight='bold', pad=15)
    ax.set_xticks(range(0, 13, 2))
    ax.set_yticks([])

    apply_theme(fig, ax)
    plt.tight_layout()

    return fig

def main():
    """Generate timing diagrams."""
    generators = {
        'ula_video_access': generate_ula_video_access,
        'snow_collision': generate_snow_collision,
    }

    # Output directory
    output_dir = 'assets'
    if len(sys.argv) > 1 and sys.argv[-1].startswith('--output='):
        output_dir = sys.argv[-1].split('=')[1]

    os.makedirs(output_dir, exist_ok=True)

    # Filter which diagrams to generate
    selected = None
    for arg in sys.argv[1:]:
        if not arg.startswith('--') and arg in generators:
            selected = [arg]
            break

    if selected is None:
        selected = list(generators.keys())

    for name in selected:
        print(f"Generating {name}...")
        fig = generators[name]()
        filepath = os.path.join(output_dir, f'{name}.svg')
        fig.savefig(filepath, format='svg', facecolor=THEME['background'],
                   edgecolor='none', bbox_inches='tight', dpi=150)
        save_meta(filepath, generators[name])
        plt.close(fig)
        print(f"  Saved: {filepath}")

if __name__ == '__main__':
    main()
